# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/Users/kartik/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

## -- vim bindings for shell -- ##
bindkey -v
## -- vim bindings for shell -- ##

## -- nvm -- ##
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
## -- nvm -- ##

## -- kafka path -- ##
export PATH="$PATH:/Users/kartik/kafka/bin" 
## -- kafka path -- ##

# alias jrun="bash ~/zsh_apac/java_run.sh"
alias vim="nvim"
# alias lsf="bash ~/zsh_apac/readlink.sh"
alias lint="prettier --write"
alias sess="tmux -CC new -s kartik"
alias gblista="git for-each-ref --sort=-committerdate refs/heads/ refs/remotes --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"
alias gblist="git for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"
alias gb="gblist"
alias gba="gblista"
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

function get_ssh_string {
	ssh -A kartik.rawat@$1
}
alias sshv="get_ssh_string $1"

# fzf specific stuff
export FZF_COMPLETION_TRIGGER='*'
bindkey ^P fzf-cd-widget

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

ssh-add ~/.ssh/id_rsa &> /dev/null
